services:
  rocp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: record-of-cashless-payment-discord-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge